workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini
    max_build_duration: 60

    environment:
      android_signing:
        - keystore_reference
      vars:
        FLUTTER_VERSION: "3.19.2"
        GRADLE_VERSION: "8.1.1"
      flutter: "3.19.2"
      java: 11

    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable
          export PATH="$PATH:$HOME/flutter/bin"
          flutter pub global activate fvm

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Run analyzer
        script: |
          flutter analyze

      - name: Run tests
        script: |
          flutter test

      - name: Build APK
        script: |
          cd android && ./gradlew assembleRelease --stacktrace --info 2>&1 | tee build.log && cd ..

    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build.log

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  build-ios:
    name: Build iOS
    instance_type: mac_mini
    max_build_duration: 120

    environment:
      ios_signing:
        - ios_app_id
      vars:
        FLUTTER_VERSION: stable

    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable
          export PATH="$PATH:$HOME/flutter/bin"

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - user@example.com
